image: python:3.6.7

services:
  - postgres:latest

variables:
  POSTGRES_DB: algonaut_test
  POSTGRES_USER: algonaut
  POSTGRES_PASSWORD: algonaut

stages:
  - test
  - deploy

before_script:
  - pip3 install virtualenv
  - make setup

test:
  stage: test
  script:
    - make test SETTINGS=gitlab-postgres

deploy:
  stage: deploy
  only:
    - /^v\d+\.\d+\.\d+$/
  script:
    - make release
