# Debug and test config
debug: true
test: false
# DB config
db:
  url: postgresql://algonaut:algonaut@localhost/algonaut_development
# CORS config
crossdomain:
  enabled: true
  max-age: 86400 #1 day
  origins: ["http://localhost:8080"] # overwrite for your production version
  allowed-headers: ['*']
# Plugin config
plugins: {}
# Authentication config
auth:
  type: worf
  config:
    url: http://localhost:5000
    version: v1
# Worker config
worker:
  type: thread
  config: {}
  schedule: {}
# API bind URL
url: http://localhost:5001
languages: [en]
