from .project import ProjectForm  # noqa
from .algorithmschema import AlgorithmSchemaForm  # noqa
from .algorithm import AlgorithmForm  # noqa
from .datapoint import DatapointForm  # noqa
from .dataschema import DataSchemaForm  # noqa
from .model import ModelForm  # noqa
from .object_role import ObjectRoleForm  # noqa
from .dataset import DatasetForm  # noqa
from .result import ResultForm  # noqa
from .datasetversion import DatasetVersionForm  # noqa
